### ISSUE TITLE
Lights turns on at startup even when said to not do it.

### ISSUE THREAD

**Issue by ZebonianJustice** [jnimmo/hass-artnet#15]
I have entered this under platform: artnet
    default_level: 0
    send_levels_on_startup: true

and then under each device i have default_level: to the DMX value that i would like the lamp to have when i turn the light to on.

Then home assistant would send the first default_level: 0 to the lights and then when i turn them on it should send the devices default_level.

Now what happens is that when i start home assistant the lights turns on automatically and it sends the devices default_level directly without considering that i have the first default_level to 0

Here is my code in configuration.yaml

`
light:
  - platform: artnet
    host: IPADRESS
    port: PORT
    dmx_channels: 9
    default_level: 0
    send_levels_on_startup: true
    devices:
      - channel: 1
        type: rgb
        name: parcan_rgb
        default_rgb: [255,255,255]
      - channel: 6
        type: dimmer
        name: parcan_mode
        default_level: 0
      - channel: 7
        type: dimmer
        name: parcan_master
        default_level: 255
      - channel: 6
        type: dimmer
        name: parcan_automixmode
        default_level: 129
      - channel: 4
        type: dimmer
        name: parcan_strobe
        default_level: 255
      - channel: 8
        type: dimmer
        name: uvpar_master
        default_level: 255
      - channel: 9
        type: dimmer
        name: uvpar_strobe
        default_level: 255

`

**Comment by jnimmo** [comment]
Hi there. I think this is expected behaviour. 
Default level wasn't intended to set what the lights should turn on as, that's up to Home Assistant. i.e. setting up a scene or action to turn the lights on to the level you want.

send_values_on_startup is for safety purposes, so if you rebooted Home Assistant while a venue was in use it isn't going to plunge the venue into darkness (as many DMX controllers do). 

Default level is to inform Home Assistant what value it should assume the light has. i.e. if we know the channel is normally at full brightness (i.e. from another DMX controller), default level means Home Assistant can show that.

The first default level is just what is used if the default level isn't set for each fixture.

I'd suggest using a Scene in Home Assistant (or action) to turn the lights on to the default levels you'd like them, rather than doing it in the fixture configuration itself. Does that help make more sense?

**Comment by jnimmo** [comment]
If you want the fixtures to be off by default - set the default values to 0, 
Then setup an action to set the lights to what you want your scene to be
In your config file:
```
scene:
  - name: Reset Lights
    entities:
      light.hall_downlights:
        state: on 
        brightness: 255
        transition: 0
```

More of a restriction based on how Home Assistant handles the UI I think
Cheers

**Comment by jnimmo** [comment]
I just spotted in the doco on https://www.home-assistant.io/components/light/ that you can setup a light_profiles.csv file which defines the default turn on values for lights -this will let you do what you want to do.
In that case, you could remove all reference to default levels from the dmx component and define what you want to happen in the light.default profile

**Comment by ZebonianJustice** [comment]
Thank you! Will give it a try :)
